name: ReactJs build and deploy

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.x
          
      - name: Install dependencies
        run: yarn
        
      - name: Build
        run: yarn build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IF }}
          username: ${{ secrets.USERNAME_IF }}
          password: ${{ secrets.PASSWORD_IF }}
          port: ${{ secrets.PORT_IF }}
          source: ".,!node_modules"
          target: "frontend/"

    
